github:  #@tijuks
Patreon: #@tijuks
open_collective: #@tijuks
ko_fi: #@tijuks
: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: #@tijuks
issuehunt: # @tijuks
fx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # @tijuks
bu
thanks_dev: # @tijuks
custom: # https://patreon.com/tijuks
